# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='id',
        ),
        migrations.AlterField(
            model_name='submenu',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Menu'),
        ),
    ]
